import { FaqItem } from './faqitem';

export const FAQITEMS: FaqItem[] = [
   { header: `Where do I drop-off my children?`, body: `All pre-registered kids will check in the Sanctuary which are zoned off for each grade level. Crew Leaders will have identifiable signs which represent which classroom your child has been assigned to from your confirmation email.`},
   { header: `When and where do I pick up my children?`, body: `With the exception of JK/SK kids, all other children will be picked up in the Sanctuary by parent or guardian, where they were dropped off in the morning. <b>Please come promptly for noon.</b><br/><br/><i>Note: For JK/SK kids, they will be picked up directly from their classroom on the main floor by parent or guardian at noon. Please ask a crew member for further details and directions.</i>`},
   { header: `What happens each day?`, body: `Kindergarten-Grade 6 children begin each morning in the Worship Center with the Opening Worship Rally. After morning worship, children will attend different rotations with classmates their own age including Bible Study, Crafts, Music, Recreation, and Snacks. The day ends with a Closing Worship Rally, and then children are dismissed at 12:00 pm.`},
   { header: `Late drop-off or early pick-up?`, body: `For safety and security reasons, we ask that you check in at the Front Office with children who arrive after 9:15 am <i>or</i> if you need to pick up a child before 12:00 pm.`},
   { header: `Is it important that I register online?`, body: `Online registration guarantees you a spot and will make the first day of VBS easier for your family. All your children will receive their pre-assigned classroom details as well as other information sent to the email address provided during registration.<br/><br/>Onsite registration will be available each day but there are no guarantees. Please ensure to register early as space is limited. All late registrations or registrations received where the classes are full, will be placed on a Waiting List.`},
   { header: `How will I know if I am on the Waiting List?`, body: `You will receive an email/phone call advising you of your status when you are placed on a Waiting List.  You will be notified promptly of any updates in your status.
`},
   { header: `Will paper-based registrations still be provided?`, body: `<b>No.</b> All registrations prior to the opening day will be accepted online only. On the opening day, we will provide paper-based registrations only if there are any available spots for the respective grade.`},
   { header: `I have a child with special needs. Can he/she still attend?`, body: `<b>Yes!</b> Please <a href="/faq#contact">contact us</a> to discuss your child's needs. We will make every effort to provide a wonderful VBS week for your child.`},
   { header: `What snacks do you provide?`, body: `Snacks vary from day-to-day, but we offer items such as fruit, yogurt, grapes, cheese and crackers, freezies and ice cream on the last day. We serve water and/or apple juice to drink. <i>All of our preparations are made in a nut-free environment</i>.
`},
   { header: `My child has food allergies. Do you provide special foods for children with allergies?`, body: `We are unable to provide special snacks for children with allergies. We ask that parents send in a separate snack for their child if they have concerns. Please keep in mind that snack time is usually only about 10 minutes long, so an appropriately-sized snack is requested.
`},
   { header: `We’ve never been to your church before, and my child is a bit nervous. May I stay with my child?`, body: `We understand that the size of our building and the number of children who are attending may be somewhat intimidating; unfortunately, the designated group rows cannot accommodate children, staff and parents. We suggest that you plan to arrive early on your child’s first day and sit with your child for a bit, as you’re welcomed in the sanctuary. Allowing your child to have time to adjust to the environment of VBS before they join their small group (by 9:00 am) in their designated zone. Parents are welcome to sit in designated areas of the church or stand at the back of the sanctuary to view our opening assembly each morning.
`},
];